GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3OTNkMjk0ZjU3YWExNmEyYjg5Y2E3MSIsImlhdCI6MTczNzgwMzYzMn0.sZPHa1A5MYU6UcrnYu1xaZQeHJYjVS8adKyHs2_3j2I
