POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Test blog with user",
    "author": "Real Person",
    "url": "unrealblogsite.org",
    "likes": 1,
    "userId": "6793d294f57aa16a2b89ca71"
}
