services:
  app:
    image: todo-app-dev
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    volumes:
      - ./todo-frontend/:/usr/src/app
    container_name: todo-app-dev
  mongo:
    image: mongo
    container_name: todo-backend-mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis:bookworm
    container_name: todo-backend-redis
    ports: 
      - 3455:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
  server:
    image: todo-dev
    container_name: todo-backend-dev
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URL=mongodb://the_username:the_password@todo-backend-mongo:27017/the_database
      - REDIS_URL=redis://todo-backend-redis:6379
    volumes:
      - ./todo-backend/:/usr/src/app
  nginx:
    image: nginx:1.20.1
    ports:
      - 8080:80
    depends_on:
      - app
      - server
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    container_name: reverse-proxy

volumes:
  mongo_data:
  redis_data:
